name: "Push changes to didmybest host"

on:
  push:
    branches:
      - "master"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SFTP
        uses: milanmk/actions-file-deployer@master
        with:
          remote-host: ${{ secrets.DIDMYBEST_HOST }}
          remote-port: 22
          remote-user: ${{ secrets.DIDMYBEST_USERNAME }}
          remote-password: ${{ secrets.DIDMYBEST_PASSWORD }}
          remote-path: "/var/www/didmybest.dk/sub_aoe_sfx"
          ssh-private-key: ${{ secrets.DIDMYBEST_SSH_KEY }}
          sync: "delta"
  update:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.DIDMYBEST_HOST }}
          username: ${{ secrets.DIDMYBEST_USERNAME }}
          password: ${{ secrets.DIDMYBEST_PASSWORD }}
          privateKey: ${{ secrets.DIDMYBEST_SSH_KEY}}
          command: |
            cd /var/www/didmybest.dk/sub_aoe_sfx
            echo '{"v":"'$(date +%s%N)'"}' > v.json
